   services:
     log-generator:
       build: .
       command: python log_generator.py
       volumes:
         - shared-logs:/app/sample-logs



     log-exporter:
       build: .
       command: python log_scan_exporter.py
       ports:
         - "8000:8000"
       volumes:
         - shared-logs:/app/sample-logs
       environment:
         - LOG_PATH=/app/sample-logs
         - LOG_PATTERN=*.log

     prometheus:
      image: prom/prometheus:latest
      ports:
        - "9090:9090"
      volumes:
        - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        - ./prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
        
     grafana:
      image: grafana/grafana:latest
      ports:
        - "3000:3000"
      volumes:
        - ./grafana/provisioning:/etc/grafana/provisioning

     alertmanager:
        image: prom/alertmanager:latest
        ports:
          - "9093:9093"
        volumes:
          - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml  
    
   volumes:
     shared-logs:

